@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Procesos de Pagos"
actor "Sistema" as A

usecase "Procesar Pagos"as CU2



A --> CU2 : Solicita Procesar Pagos
CU2 --> Sistema : Valida y Procesa Pagos



@enduml