@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Eliminar Usuario"

actor "Administrador" as A

usecase "Eliminar usuario" as CU2



A --> CU2 : Solicita eliminar usuario
CU2 --> Sistema : Valida y elimina el usuario




@enduml