@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Asignar Técnico"

actor "Supervisor" as A

usecase "Asignar Técnico" as CU2



A --> CU2 : Solicita asignar técnico
CU2 --> Sistema : Valida y asigna el técnico




@enduml