@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Solicitar Repuesto"

actor "Supervisor" as A

usecase "Solicitar Repuesto" as CU2



A --> CU2 : Solicita solicitar repuesto
CU2 --> Sistema : Valida y crea la solicitud de repuesto




@enduml