@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Decidir Presupuesto"

actor "Cliente" as A

usecase "Decidir Presupuesto" as CU2



A --> CU2 : Solicita decidir presupuesto
CU2 --> Sistema : Valida y crea la decisión de presupuesto




@enduml