@startuml
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle
title "Enviar Notificaciones"

actor "Admin" as A

usecase "Enviar Notificaciones"as CU2



A --> CU2 : Solicita Enviar Notificacion
CU2 --> Sistema : Valida y Envia Notificaciones



@enduml